# Generated by Django 2.2.6 on 2019-11-23 09:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_auto_20191123_1214'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='BlogAuthor',
        ),
    ]
